export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS= "LOGIN_SUCCESS"
export const LOGIN_FAIL= "LOGIN_FAIL"

export const REGISTER_USER_REQUEST="REGISTER_USER_REQUEST"
export const REGISTER_USER_SUCCESS="REGISTER_USER_SUCCESS"
export const REGISTER_USER_FAIL="REGISTER_USER_FAIL"

//export const USER_UPDATE_REQUEST="USER_UPDATE_REQUEST"
//export const USER_UPDATE_SUCCESS="USER_UPDATE_SUCCESS"
//export const USER_UPDATE_FAIL="USER_UPDATE_FAIL"

export const CLEAR_ERRORS="CLEAR_ERRORS"